/**
 * Built-in stock universe (NIFTY 100 + popular midcaps) used for the market
 * screen, gainers/losers and search suggestions. Anything else is reachable
 * through live search. Symbols are Yahoo-style (.NS = NSE, .BO = BSE).
 */

const INDICES = [
  { symbol: '^NSEI', name: 'NIFTY 50', exchange: 'NSE' },
  { symbol: '^BSESN', name: 'SENSEX', exchange: 'BSE' },
  { symbol: '^NSEBANK', name: 'NIFTY BANK', exchange: 'NSE' },
  { symbol: '^CNXIT', name: 'NIFTY IT', exchange: 'NSE' },
  { symbol: 'NIFTY_FIN_SERVICE.NS', name: 'FINNIFTY', exchange: 'NSE' },
  { symbol: '^CNXAUTO', name: 'NIFTY AUTO', exchange: 'NSE' },
  { symbol: '^CNXPHARMA', name: 'NIFTY PHARMA', exchange: 'NSE' },
  { symbol: '^CNXFMCG', name: 'NIFTY FMCG', exchange: 'NSE' },
  { symbol: '^CNXMETAL', name: 'NIFTY METAL', exchange: 'NSE' },
  { symbol: 'NIFTY_MIDCAP_100.NS', name: 'NIFTY MIDCAP 100', exchange: 'NSE' },
];

const UNIVERSE = [
  ['RELIANCE.NS', 'Reliance Industries', 'Oil & Gas'],
  ['TCS.NS', 'Tata Consultancy Services', 'IT'],
  ['HDFCBANK.NS', 'HDFC Bank', 'Banking'],
  ['ICICIBANK.NS', 'ICICI Bank', 'Banking'],
  ['BHARTIARTL.NS', 'Bharti Airtel', 'Telecom'],
  ['SBIN.NS', 'State Bank of India', 'Banking'],
  ['INFY.NS', 'Infosys', 'IT'],
  ['LICI.NS', 'Life Insurance Corporation', 'Insurance'],
  ['ITC.NS', 'ITC', 'FMCG'],
  ['HINDUNILVR.NS', 'Hindustan Unilever', 'FMCG'],
  ['LT.NS', 'Larsen & Toubro', 'Infrastructure'],
  ['BAJFINANCE.NS', 'Bajaj Finance', 'NBFC'],
  ['HCLTECH.NS', 'HCL Technologies', 'IT'],
  ['MARUTI.NS', 'Maruti Suzuki', 'Auto'],
  ['SUNPHARMA.NS', 'Sun Pharma', 'Pharma'],
  ['KOTAKBANK.NS', 'Kotak Mahindra Bank', 'Banking'],
  ['M&M.NS', 'Mahindra & Mahindra', 'Auto'],
  ['AXISBANK.NS', 'Axis Bank', 'Banking'],
  ['ULTRACEMCO.NS', 'UltraTech Cement', 'Cement'],
  ['NTPC.NS', 'NTPC', 'Power'],
  ['TITAN.NS', 'Titan Company', 'Consumer'],
  ['ONGC.NS', 'ONGC', 'Oil & Gas'],
  ['BAJAJFINSV.NS', 'Bajaj Finserv', 'NBFC'],
  ['ADANIENT.NS', 'Adani Enterprises', 'Conglomerate'],
  ['ADANIPORTS.NS', 'Adani Ports & SEZ', 'Infrastructure'],
  ['POWERGRID.NS', 'Power Grid Corp', 'Power'],
  ['ASIANPAINT.NS', 'Asian Paints', 'Consumer'],
  ['WIPRO.NS', 'Wipro', 'IT'],
  ['JSWSTEEL.NS', 'JSW Steel', 'Metals'],
  ['TMCV.NS', 'Tata Motors Commercial Vehicles', 'Auto'],
  ['TATASTEEL.NS', 'Tata Steel', 'Metals'],
  ['COALINDIA.NS', 'Coal India', 'Mining'],
  ['NESTLEIND.NS', 'Nestle India', 'FMCG'],
  ['BAJAJ-AUTO.NS', 'Bajaj Auto', 'Auto'],
  ['HINDALCO.NS', 'Hindalco Industries', 'Metals'],
  ['GRASIM.NS', 'Grasim Industries', 'Cement'],
  ['HDFCLIFE.NS', 'HDFC Life Insurance', 'Insurance'],
  ['SBILIFE.NS', 'SBI Life Insurance', 'Insurance'],
  ['TECHM.NS', 'Tech Mahindra', 'IT'],
  ['EICHERMOT.NS', 'Eicher Motors', 'Auto'],
  ['DRREDDY.NS', "Dr Reddy's Labs", 'Pharma'],
  ['CIPLA.NS', 'Cipla', 'Pharma'],
  ['TATACONSUM.NS', 'Tata Consumer Products', 'FMCG'],
  ['BRITANNIA.NS', 'Britannia Industries', 'FMCG'],
  ['APOLLOHOSP.NS', 'Apollo Hospitals', 'Healthcare'],
  ['DIVISLAB.NS', "Divi's Laboratories", 'Pharma'],
  ['INDUSINDBK.NS', 'IndusInd Bank', 'Banking'],
  ['HEROMOTOCO.NS', 'Hero MotoCorp', 'Auto'],
  ['SHRIRAMFIN.NS', 'Shriram Finance', 'NBFC'],
  ['BPCL.NS', 'BPCL', 'Oil & Gas'],
  ['VEDL.NS', 'Vedanta', 'Metals'],
  ['ETERNAL.NS', 'Eternal (Zomato)', 'Consumer Tech'],
  ['HAL.NS', 'Hindustan Aeronautics', 'Defence'],
  ['DLF.NS', 'DLF', 'Realty'],
  ['ADANIGREEN.NS', 'Adani Green Energy', 'Power'],
  ['ADANIPOWER.NS', 'Adani Power', 'Power'],
  ['JIOFIN.NS', 'Jio Financial Services', 'NBFC'],
  ['IOC.NS', 'Indian Oil Corp', 'Oil & Gas'],
  ['BEL.NS', 'Bharat Electronics', 'Defence'],
  ['TRENT.NS', 'Trent', 'Retail'],
  ['VBL.NS', 'Varun Beverages', 'FMCG'],
  ['PIDILITIND.NS', 'Pidilite Industries', 'Chemicals'],
  ['SIEMENS.NS', 'Siemens', 'Capital Goods'],
  ['GODREJCP.NS', 'Godrej Consumer', 'FMCG'],
  ['AMBUJACEM.NS', 'Ambuja Cements', 'Cement'],
  ['GAIL.NS', 'GAIL India', 'Oil & Gas'],
  ['DABUR.NS', 'Dabur India', 'FMCG'],
  ['PNB.NS', 'Punjab National Bank', 'Banking'],
  ['BANKBARODA.NS', 'Bank of Baroda', 'Banking'],
  ['LTM.NS', 'LTM Limited (LTIMindtree)', 'IT'],
  ['ABB.NS', 'ABB India', 'Capital Goods'],
  ['CHOLAFIN.NS', 'Cholamandalam Finance', 'NBFC'],
  ['HAVELLS.NS', 'Havells India', 'Consumer Durables'],
  ['TVSMOTOR.NS', 'TVS Motor', 'Auto'],
  ['CANBK.NS', 'Canara Bank', 'Banking'],
  ['MOTHERSON.NS', 'Samvardhana Motherson', 'Auto Parts'],
  ['HINDZINC.NS', 'Hindustan Zinc', 'Metals'],
  ['UNITDSPR.NS', 'United Spirits', 'Beverages'],
  ['BOSCHLTD.NS', 'Bosch', 'Auto Parts'],
  ['ZYDUSLIFE.NS', 'Zydus Lifesciences', 'Pharma'],
  ['CUMMINSIND.NS', 'Cummins India', 'Capital Goods'],
  ['LUPIN.NS', 'Lupin', 'Pharma'],
  ['POLYCAB.NS', 'Polycab India', 'Consumer Durables'],
  ['INDIGO.NS', 'InterGlobe Aviation', 'Aviation'],
  ['NAUKRI.NS', 'Info Edge (Naukri)', 'Internet'],
  ['BHEL.NS', 'BHEL', 'Capital Goods'],
  ['RECLTD.NS', 'REC Limited', 'NBFC'],
  ['PFC.NS', 'Power Finance Corp', 'NBFC'],
  ['IRFC.NS', 'Indian Railway Finance', 'NBFC'],
  ['IRCTC.NS', 'IRCTC', 'Travel'],
  ['NHPC.NS', 'NHPC', 'Power'],
  ['TATAPOWER.NS', 'Tata Power', 'Power'],
  ['JINDALSTEL.NS', 'Jindal Steel & Power', 'Metals'],
  ['SAIL.NS', 'SAIL', 'Metals'],
  ['NMDC.NS', 'NMDC', 'Mining'],
  ['IDFCFIRSTB.NS', 'IDFC First Bank', 'Banking'],
  ['YESBANK.NS', 'Yes Bank', 'Banking'],
  ['SUZLON.NS', 'Suzlon Energy', 'Power'],
  ['PAYTM.NS', 'One97 (Paytm)', 'Fintech'],
  ['POLICYBZR.NS', 'PB Fintech (PolicyBazaar)', 'Fintech'],
  ['DMART.NS', 'Avenue Supermarts (DMart)', 'Retail'],
  ['BSE.NS', 'BSE Limited', 'Exchanges'],
  ['MCX.NS', 'MCX India', 'Exchanges'],
  ['CDSL.NS', 'CDSL', 'Depositories'],
  ['ANGELONE.NS', 'Angel One', 'Broking'],
  ['TATAELXSI.NS', 'Tata Elxsi', 'IT'],
  ['PERSISTENT.NS', 'Persistent Systems', 'IT'],
  ['COFORGE.NS', 'Coforge', 'IT'],
  ['MPHASIS.NS', 'Mphasis', 'IT'],
  ['ASHOKLEY.NS', 'Ashok Leyland', 'Auto'],
  ['BHARATFORG.NS', 'Bharat Forge', 'Auto Parts'],
  ['MAZDOCK.NS', 'Mazagon Dock', 'Defence'],
  ['COCHINSHIP.NS', 'Cochin Shipyard', 'Defence'],
  ['RVNL.NS', 'Rail Vikas Nigam', 'Infrastructure'],
  ['SWIGGY.NS', 'Swiggy', 'Consumer Tech'],
  ['NYKAA.NS', 'FSN E-Commerce (Nykaa)', 'Retail'],
  ['DELHIVERY.NS', 'Delhivery', 'Logistics'],
  ['ABCAPITAL.NS', 'Aditya Birla Capital', 'NBFC'],
  ['MUTHOOTFIN.NS', 'Muthoot Finance', 'NBFC'],
  ['SRF.NS', 'SRF', 'Chemicals'],
  ['UPL.NS', 'UPL', 'Agrochemicals'],
  ['COLPAL.NS', 'Colgate-Palmolive India', 'FMCG'],
  ['MARICO.NS', 'Marico', 'FMCG'],
  ['BERGEPAINT.NS', 'Berger Paints', 'Consumer'],
  ['ASTRAL.NS', 'Astral', 'Building Materials'],
  ['DIXON.NS', 'Dixon Technologies', 'Electronics'],
  ['KALYANKJIL.NS', 'Kalyan Jewellers', 'Consumer'],
  ['SHREECEM.NS', 'Shree Cement', 'Cement'],
  ['TORNTPHARM.NS', 'Torrent Pharma', 'Pharma'],
  ['MAXHEALTH.NS', 'Max Healthcare', 'Healthcare'],
  ['FORTIS.NS', 'Fortis Healthcare', 'Healthcare'],
  ['AUROPHARMA.NS', 'Aurobindo Pharma', 'Pharma'],
  ['ALKEM.NS', 'Alkem Laboratories', 'Pharma'],
  ['BIOCON.NS', 'Biocon', 'Pharma'],
  ['OFSS.NS', 'Oracle Financial Services', 'IT'],
  ['ICICIGI.NS', 'ICICI Lombard', 'Insurance'],
  ['ICICIPRULI.NS', 'ICICI Prudential Life', 'Insurance'],
  ['AUBANK.NS', 'AU Small Finance Bank', 'Banking'],
  ['FEDERALBNK.NS', 'Federal Bank', 'Banking'],
  ['UNIONBANK.NS', 'Union Bank of India', 'Banking'],
  ['IDBI.NS', 'IDBI Bank', 'Banking'],
  ['LICHSGFIN.NS', 'LIC Housing Finance', 'NBFC'],
  ['MANAPPURAM.NS', 'Manappuram Finance', 'NBFC'],
  ['GMRAIRPORT.NS', 'GMR Airports', 'Infrastructure'],
  ['PGEL.NS', 'PG Electroplast', 'Electronics'],
  ['KAYNES.NS', 'Kaynes Technology', 'Electronics'],
  ['SYRMA.NS', 'Syrma SGS Technology', 'Electronics'],
  ['OLAELEC.NS', 'Ola Electric', 'Auto'],
  ['HYUNDAI.NS', 'Hyundai Motor India', 'Auto'],
  ['LODHA.NS', 'Macrotech (Lodha)', 'Realty'],
  ['GODREJPROP.NS', 'Godrej Properties', 'Realty'],
  ['OBEROIRLTY.NS', 'Oberoi Realty', 'Realty'],
  ['PRESTIGE.NS', 'Prestige Estates', 'Realty'],
  ['INDHOTEL.NS', 'Indian Hotels (Taj)', 'Hotels'],
  ['EIHOTEL.NS', 'EIH (Oberoi Hotels)', 'Hotels'],
].map(([symbol, name, sector]) => ({ symbol, name, sector }));

module.exports = { INDICES, UNIVERSE };
